name: qa guru diploma nv
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pwndv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
        #делаю чекаут кода
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          node-version: lts/*
      - name: Установить все пакеты из package.json
        run: npm ci
      - name: Установить pw
        run: npx playwright install --with-deps        
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
          
        #новый прогон тестов
      - name: Run Playwright tests
        run: allurectl watch -- npx playwright test
        env:
          ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
          ALLURE_RESULTS: allure-results
          ALLURE_LAUNCH_NAME: "Playwright CI #${{ github.run_number }}"
        continue-on-error: true
        if: always()
        
        #генерация отчета
      - name: Generate Allure report (single file)
        if: always()
        run: npx allure awesome ./allure-results --single-file
        continue-on-error: true
        
        #сохраняю артефакты
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        if: always()
        continue-on-error: true
        with:
          name: allure single file
          path: |
            allure-report/index.html
            allure-results
            playwright-report

        #отправка отчета в телегу
      - name: Send Allure report to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -f allure-report/index.html ]; then
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
              -F chat_id="${TELEGRAM_CHAT_ID}" \
              -F document=@allure-report/index.html \
              -F caption="Allure report (single-file)"
          fi

        # Отправка текстового уведомления в Telegram
      - name: Send test summary to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: node scripts/telegram-summary.js
